### ISSUE TITLE
Getting error while running refresh.py 

### ISSUE THREAD

**Issue by ayush571995** [kuutsav/leetcode-compensation#33]
I followed steps and ran the command python3 leetcomp/refresh.py

Getting error

python3 .\leetcomp\parse.py
Traceback (most recent call last):
  File "C:\path_to_poject\leetcode-compensation\leetcomp\parse.py", line 8, in <module>
    from leetcomp.utils import (
  File "C:\path_to_poject\leetcode-compensation\leetcomp\utils.py", line 62
    match inf_engine.lower():
          ^

**Comment by kuutsav** [comment]
Hey, I've updated the "Updating data" section to highlight the need for llm inference which was probably the issue you were facing.
